FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app
COPY /home/runner/work/ActionTest/ActionTest/ActionTest/bin/Release/net8.0/publish/ /app/
ENTRYPOINT ["dotnet", "ActionTest.dll"]
