# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build    
      run: dotnet build --configuration Release
    - name: Publish
      run: dotnet publish --configuration Release 
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: /home/runner/work/ActionTest/ActionTest/ActionTest/bin/Release/net8.0/ # Pfad zu den gebauten Artefakten
    
    - name: build docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)      
